version: "3.8"

networks:
  network1:
    name: ${NETWORK1}

services:

  app:
    image: deathstar.app
    expose:
      - 8080
      - 7788
    # ports:
    #   - 7701:7788
    #   - 8801:8080
    networks:
      - network1
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui-multiplayer:
    image: deathstar.ui-multiplayer
    expose:
      - 80
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui-stats:
    image: deathstar.ui-stats
    expose:
      - 80
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ui-graphiql:
    image: deathstar.ui-graphiql
    expose:
      - 80
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        

  ui-identity:
    image: deathstar.ui-identity
    expose:
      - 80
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M